# ----------------------------------------
# Created on: Sun Feb 12 19:26:32 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "C:/Users/93462/PdsProject/fpga-learn/project/pango_sim_libraries/usim"
vmap  adc "C:/Users/93462/PdsProject/fpga-learn/project/pango_sim_libraries/adc"
vmap  ddrc "C:/Users/93462/PdsProject/fpga-learn/project/pango_sim_libraries/ddrc"
vmap  ddrphy "C:/Users/93462/PdsProject/fpga-learn/project/pango_sim_libraries/ddrphy"
vmap  hsst_e2 "C:/Users/93462/PdsProject/fpga-learn/project/pango_sim_libraries/hsst_e2"
vmap  iolhr_dft "C:/Users/93462/PdsProject/fpga-learn/project/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "C:/Users/93462/PdsProject/fpga-learn/project/pango_sim_libraries/ipal_e1"
vmap  pciegen2 "C:/Users/93462/PdsProject/fpga-learn/project/pango_sim_libraries/pciegen2"
vlog   "PresentFpga_syn.vm" -work work
vlog   "C:/Users/93462/PdsProject/fpga-learn/sim/Present_tb.v" -work work

# ----------------------------------------
