# ----------------------------------------
# Created on: Sun Feb 12 16:54:46 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vlog   "C:/Users/93462/PdsProject/fpga-learn/rtl/PresentFpga.v" -work work
vlog   "C:/Users/93462/PdsProject/fpga-learn/sim/Present_tb.v" -work work

# ----------------------------------------
