# ----------------------------------------
# Created on: Sun Feb 12 16:54:46 2023
# Auto generated by Pango
# ----------------------------------------

vsim  -novopt  -L work test
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
